---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Zot registry
  ansible.builtin.systemd_service:
    name: "{{ zot_registry_service_name }}"
    state: restarted
  when:
    - zot_registry_service_enabled | bool
    - not ansible_check_mode
