---
rke2_install_script_url: https://get.rke2.io
rke2_install_script_path: /usr/local/sbin/rke2-install.sh
rke2_binary_path: /usr/bin/rke2
rke2_channel: stable
rke2_version: ""
rke2_allow_unpinned: false

rke2_config_dir: /etc/rancher/rke2
rke2_config_path: "{{ rke2_config_dir }}/config.yaml"
rke2_registries_path: "{{ rke2_config_dir }}/registries.yaml"
rke2_token_path: "{{ rke2_config_dir }}/cluster-token"
rke2_token_src: ""

rke2_cluster_group: rke2_cluster
rke2_server_group: rke2_servers
rke2_agent_group: rke2_agents
rke2_bootstrap_host: "{{ groups[rke2_server_group][0] }}"
rke2_bootstrap_host_address: "{{ hostvars[rke2_bootstrap_host].ansible_host | default(rke2_bootstrap_host) }}"
rke2_server_url: "https://{{ rke2_bootstrap_host_address }}:9345"

rke2_node_role: "{{ 'server' if inventory_hostname in groups.get(rke2_server_group, []) else 'agent' }}"
rke2_service_name: "{{ 'rke2-server.service' if rke2_node_role == 'server' else 'rke2-agent.service' }}"
rke2_service_enabled: true
rke2_service_state: started

rke2_node_name: "{{ inventory_hostname }}"
rke2_node_ip: "{{ ansible_host | default(inventory_hostname) }}"
rke2_selinux: true
rke2_write_kubeconfig_mode: "0600"
rke2_kernel_modules:
  - br_netfilter
  - overlay
rke2_kernel_module_packages:
  - kernel-modules-extra
rke2_kernel_module_package_state: present
rke2_reboot_for_kernel_modules: false
rke2_kernel_module_reboot_timeout: 900
rke2_kernel_module_reboot_marker_path: /var/lib/rke2-kernel-reboot-target
rke2_kernel_module_readiness_marker_path: /var/lib/rke2-kernel-reboot-readiness
rke2_grubby_path: /usr/sbin/grubby
rke2_sysctl:
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"
  net.ipv4.ip_forward: "1"

rke2_cni: calico
platform_ingress_controller: traefik
rke2_disable: []
rke2_tls_sans: []
rke2_extra_config: {}

rke2_server_manifest_dir: /var/lib/rancher/rke2/server/manifests
rke2_traefik_helmchartconfig_path: "{{ rke2_server_manifest_dir }}/rke2-traefik-config.yaml"
rke2_kong_manifest_path: "{{ rke2_server_manifest_dir }}/kong-ingress.yaml"
rke2_kubectl: /var/lib/rancher/rke2/bin/kubectl
rke2_kubeconfig: /etc/rancher/rke2/rke2.yaml
rke2_traefik_node_port_min: 30000
rke2_traefik_node_port_max: 32767
rke2_traefik_http_node_port: 30080
rke2_traefik_https_node_port: 30443

rke2_registry_mirrors: {}
rke2_registry_configs: {}
rke2_registry_ca_src: ""
rke2_registry_ca_path: "{{ rke2_config_dir }}/registry-ca.crt"

rke2_firewalld_manage: true
rke2_firewalld_cluster_sources: []
rke2_firewalld_api_sources: []
rke2_firewalld_api_ports:
  - "6443"
rke2_wait_for_supervisor_timeout: 600
