---
- name: Reload OpenBao HAProxy
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/reload.yml"
  when:
    - openbao_haproxy_service_enabled | bool
    - openbao_haproxy_service_state == 'started'
    - not ansible_check_mode
