---
gitlab_runner_image: >-
  docker.io/gitlab/gitlab-runner:alpine-v18.11.3@sha256:904cc94dc8417152685f62c4c1a1add19ad2d82947ca7aead844895e16128f1e
gitlab_runner_container_name: gitlab-runner
gitlab_runner_quadlet_name: gitlab-runner.container
gitlab_runner_service_name: gitlab-runner.service

gitlab_runner_config_dir: /etc/gitlab-runner
gitlab_runner_config_path: "{{ gitlab_runner_config_dir }}/config.toml"
gitlab_runner_certs_dir: "{{ gitlab_runner_config_dir }}/certs"
gitlab_runner_data_dir: /var/lib/gitlab-runner

gitlab_runner_gitlab_url: ""
gitlab_runner_token_src: ""
gitlab_runner_name: "{{ inventory_hostname }}"
gitlab_runner_executor: shell
gitlab_runner_tags: []
gitlab_runner_registration_extra_args: []
gitlab_runner_force_register: false
gitlab_runner_defer_backup_cleanup: false

gitlab_runner_podman_socket_enabled: false
gitlab_runner_podman_socket_host_path: /run/podman/podman.sock
gitlab_runner_podman_socket_container_path: /run/podman/podman.sock

gitlab_runner_docker_host: "unix://{{ gitlab_runner_podman_socket_container_path }}"
gitlab_runner_docker_image: ""
gitlab_runner_docker_helper_image: ""
gitlab_runner_docker_pull_policy: always
gitlab_runner_docker_network_per_build: true
gitlab_runner_docker_volumes:
  - /cache

gitlab_runner_tls_ca_cert_src: ""
gitlab_runner_tls_ca_cert_sha256: ""
gitlab_runner_tls_ca_cert_path: "{{ gitlab_runner_certs_dir }}/gitlab-ca.crt"
gitlab_runner_container_tls_ca_cert_path: /etc/gitlab-runner/certs/gitlab-ca.crt

gitlab_runner_quadlet_dir: "{{ podman_host_quadlet_dir | default('/etc/containers/systemd') }}"
gitlab_runner_quadlet_path: "{{ gitlab_runner_quadlet_dir }}/{{ gitlab_runner_quadlet_name }}"
gitlab_runner_quadlet_wants: network-online.target
gitlab_runner_quadlet_after: network-online.target
gitlab_runner_quadlet_restart_policy: always
gitlab_runner_quadlet_volume_label: Z

gitlab_runner_service_enabled: true
gitlab_runner_service_state: started
