---
- name: Configure RKE2 server nodes
  hosts: rke2_servers
  become: true
  serial: 1
  any_errors_fatal: true
  roles:
    - firewalld
    - rke2

- name: Configure RKE2 agent nodes
  hosts: rke2_agents
  become: true
  serial: 1
  any_errors_fatal: true
  roles:
    - firewalld
    - rke2
